build(spotless): align google-java-format versions (#743)
Not sure if I'm the only one getting such spotless linting errors:

```
* What went wrong:
Execution failed for task ':examples:substrait-spark:spotlessJavaCheck'.
> There were 10 lint error(s), they must be fixed or suppressed.
  src/main/java/io/substrait/examples/App.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/SparkConsumeSubstrait.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/SparkDataset.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/SparkHelper.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/SparkSQL.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/util/ExpressionStringify.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/util/FunctionArgStringify.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/util/ParentStringify.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/util/SubstraitStringify.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  src/main/java/io/substrait/examples/util/TypeStringify.java:LINE_UNDEFINED google-java-format(java.lang.NoClassDefFoundError) com/google/common/collect/Iterables$4 (...)
  Resolve these lints or suppress with `suppressLintsFor`
```

I found out this is due to `kfmt` and the `java` formatting in spotless
using different `google-java-foramt` versions. This PR aligns the
`google-java-format` versions which fixes these "lint" errors.

Signed-off-by: Niels Pardon <par@zurich.ibm.com>